# Generated by Django 5.1.3 on 2025-04-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_users_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.user'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
